       function RampWaveform=GenRampWaveform(RetraceLength, ClearRampLength, SettleLength, AcqDelayLength, PreviousScanRange,PreviousScanOffset, NextScanRange, NextScanOffset)
             A0=PreviousScanRange+PreviousScanOffset+0.5*PreviousScanRange/ClearRampLength*SettleLength;
             A1=(RetraceLength+SettleLength+AcqDelayLength)*PreviousScanRange/ClearRampLength...
                +0.5*(NextScanRange/ClearRampLength-PreviousScanRange/ClearRampLength)*AcqDelayLength...
                +0.5*(NextScanRange/ClearRampLength-PreviousScanRange/ClearRampLength)*(RetraceLength+SettleLength+AcqDelayLength)...
                +PreviousScanRange-(NextScanOffset-PreviousScanOffset);
             A2=-A1/(2*pi);
             W=2*pi/RetraceLength;
             RetracePart=zeros(RetraceLength,1);
             for i=1:RetraceLength
                 RetracePart(i)=A2*((i-1)*W-sin((i-1)*W))...
                                +0.5*(i-1)^2*(NextScanRange/ClearRampLength-PreviousScanRange/ClearRampLength)/RetraceLength...
                                +(i-1)*PreviousScanRange/ClearRampLength...
                                +A0;
             end
             LineWaveformLength=ClearRampLength+SettleLength+AcqDelayLength;
           % LineWaveformLength=LineWaveformLength+rem(LineWaveformLength,2);
             RampPart=zeros(LineWaveformLength,1);
             for i=1:LineWaveformLength
             RampPart(i)=(i-1)*PreviousScanRange/ClearRampLength...
                         -0.5*PreviousScanRange/ClearRampLength*SettleLength...
                         -PreviousScanRange/ClearRampLength*AcqDelayLength...
                         +PreviousScanOffset;
             end
             RampWaveform=[RampPart; RetracePart];
        end