function RetraceWaveform = GenRetraceWaveform(RetraceLength, ClearRampLength, SettleLength, AcqDelayLength, PreviousScanRange,PreviousScanOffset, NextScanRange, NextScanOffset)
            A0=PreviousScanRange+PreviousScanOffset+0.5*PreviousScanRange/ClearRampLength*SettleLength;
            A1=(RetraceLength+SettleLength+AcqDelayLength)*PreviousScanRange/ClearRampLength...
               +0.5*(NextScanRange/ClearRampLength-PreviousScanRange/ClearRampLength)*AcqDelayLength...
               +0.5*(NextScanRange/ClearRampLength-PreviousScanRange/ClearRampLength)*(RetraceLength+SettleLength+AcqDelayLength)...
               +PreviousScanRange-(NextScanOffset-PreviousScanOffset);
            A2=-A1/(2*pi);
            W=2*pi/RetraceLength;
            RetraceWaveform=zeros(RetraceLength,1);
            for i=1:RetraceLength
                RetraceWaveform(i)=A2*((i-1)*W-sin((i-1)*W))...
                                   +0.5*(i-1)^2*(NextScanRange/ClearRampLength-PreviousScanRange/ClearRampLength)/RetraceLength...
                                   +(i-1)*PreviousScanRange/ClearRampLength...
                                   +A0;
            end
end 
        